[namespace]
default = "command_nexus"

[env]
account_address = ""
private_key = ""
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[world]
seed = "command_nexus"
name = "Command Nexus"
description = "Become a commander"
cover_uri = "file://assets/bg.webp"
website = "https://command-nexus.vercel.app/"


[writers]
"command_nexus" = ["command_nexus-arena","command_nexus-nexus"]
