[package]
cairo-version = "=2.8.4"
name = "command_nexus"
version = "1.0.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawn = "sozo execute command_nexus-actions spawn --wait"    # scarb run spawn
move = "sozo execute command_nexus-actions move -c 1 --wait" # scarb run move

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.1" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.0.1" }


[profile.sepolia]