kind = "DojoModel"
class_hash = "0x7c864c99cbeb904980ea7c47ba9f147fa2b3d2b2348405035268ff9f50eb2ad"
original_class_hash = "0x7c864c99cbeb904980ea7c47ba9f147fa2b3d2b2348405035268ff9f50eb2ad"
abi = "manifests/sepolia/abis/base/models/contracts_models_assets_communication_control_center.json"
name = "contracts::models::assets::communication::control_center"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "center_id"
type = "u32"
key = false

[[members]]
name = "center_name"
type = "felt252"
key = false

[[members]]
name = "location"
type = "felt252"
key = false

[[members]]
name = "status"
type = "felt252"
key = false
