kind = "DojoModel"
class_hash = "0x75c92120c915547d0f170aaf7d1cedb18f34922ae3000c55ea22029c0530c47"
original_class_hash = "0x75c92120c915547d0f170aaf7d1cedb18f34922ae3000c55ea22029c0530c47"
abi = "manifests/sepolia/abis/base/models/contracts_models_units_ship_ship_accessories.json"
name = "contracts::models::units::ship::ship_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "fuel"
type = "u32"
key = false

[[members]]
name = "ammunition"
type = "u32"
key = false
