kind = "DojoModel"
class_hash = "0x43c1754a7ed3955ac0dcadad25dcb16b676714772cccd09f38892e3c2ea3548"
original_class_hash = "0x43c1754a7ed3955ac0dcadad25dcb16b676714772cccd09f38892e3c2ea3548"
abi = "manifests/sepolia/abis/base/models/contracts_models_assets_communication_cable.json"
name = "contracts::models::assets::communication::cable"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "cable_id"
type = "u32"
key = false

[[members]]
name = "cable_name"
type = "felt252"
key = false

[[members]]
name = "length"
type = "u32"
key = false

[[members]]
name = "status"
type = "felt252"
key = false
