kind = "DojoModel"
class_hash = "0x37f2b04a7f74c398c6243dc5f09ad86b7170637a933baf289bfae1d003a75ff"
original_class_hash = "0x37f2b04a7f74c398c6243dc5f09ad86b7170637a933baf289bfae1d003a75ff"
abi = "manifests/sepolia/abis/base/models/contracts_models_units_infantry_infantry.json"
name = "contracts::models::units::infantry::infantry"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "accessories"
type = "InfantryAccessories"
key = false

[[members]]
name = "health"
type = "InfantryHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false
