kind = "DojoModel"
class_hash = "0x4a54d60cf3d7e639535aec4c3c57a8a9d1e9d35635fb482b92cdb63f67eab64"
original_class_hash = "0x4a54d60cf3d7e639535aec4c3c57a8a9d1e9d35635fb482b92cdb63f67eab64"
abi = "manifests/sepolia/abis/base/models/contracts_models_assets_communication_communication.json"
name = "contracts::models::assets::communication::communication"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "cable"
type = "Cable"
key = false

[[members]]
name = "communication_tower"
type = "CommunicationTower"
key = false

[[members]]
name = "satellite_dish"
type = "SatelliteDish"
key = false

[[members]]
name = "relay_station"
type = "RelayStation"
key = false

[[members]]
name = "control_center"
type = "ControlCenter"
key = false
