kind = "DojoModel"
class_hash = "0xefe1682acca4133ea13b82981ae298b7458f2b1ad9a9aa0ee6ca8e3545cfe4"
original_class_hash = "0xefe1682acca4133ea13b82981ae298b7458f2b1ad9a9aa0ee6ca8e3545cfe4"
abi = "manifests/sepolia/abis/base/models/contracts_models_assets_transportation_seaport.json"
name = "contracts::models::assets::transportation::seaport"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "seaport_id"
type = "u32"
key = false

[[members]]
name = "seaport_name"
type = "felt252"
key = false
