kind = "DojoModel"
class_hash = "0x6ea72f89d699986cd96b596a7f18244e565727eb0150413c83eb0eb40bb52b"
original_class_hash = "0x6ea72f89d699986cd96b596a7f18244e565727eb0150413c83eb0eb40bb52b"
abi = "manifests/sepolia/abis/base/models/contracts_models_assets_communication_satellite_dish.json"
name = "contracts::models::assets::communication::satellite_dish"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "dish_id"
type = "u32"
key = false

[[members]]
name = "dish_name"
type = "felt252"
key = false

[[members]]
name = "diameter"
type = "u32"
key = false

[[members]]
name = "status"
type = "felt252"
key = false
