kind = "DojoModel"
class_hash = "0x6c10d91ef435817e54fe87017bc25491e7732e00cffa1c68e004a4ae562a4a9"
original_class_hash = "0x6c10d91ef435817e54fe87017bc25491e7732e00cffa1c68e004a4ae562a4a9"
abi = "manifests/dev/abis/base/models/bootcamp_models_infantry_infantry_accessories.json"
name = "bootcamp::models::infantry::infantry_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "ammunition"
type = "u32"
key = false

[[members]]
name = "first_aid_kit"
type = "u32"
key = false

[[members]]
name = "molotov"
type = "u32"
key = false

[[members]]
name = "grenade"
type = "u32"
key = false
