kind = "DojoModel"
class_hash = "0x398f02bb9e074f3076d1359a6e1645f3cbff458db97621f30a2facf3a41b24f"
original_class_hash = "0x398f02bb9e074f3076d1359a6e1645f3cbff458db97621f30a2facf3a41b24f"
abi = "manifests/dev/abis/base/models/contracts_models_assets_financial_investment_firm.json"
name = "contracts::models::assets::financial::investment_firm"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "firm_id"
type = "u32"
key = false

[[members]]
name = "firm_name"
type = "felt252"
key = false

[[members]]
name = "assets_under_management"
type = "u32"
key = false

[[members]]
name = "active_investments"
type = "u32"
key = false

[[members]]
name = "status"
type = "FinancialStatus"
key = false
