kind = "DojoModel"
class_hash = "0x1f2dad7f4877ae80e3e84dc3b774e30cb340e46cabfd9469bab84138a0abe89"
original_class_hash = "0x1f2dad7f4877ae80e3e84dc3b774e30cb340e46cabfd9469bab84138a0abe89"
abi = "manifests/dev/abis/base/models/contracts_models_transportation_seaport.json"
name = "contracts::models::transportation::seaport"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "seaport_id"
type = "u32"
key = false

[[members]]
name = "seaport_name"
type = "felt252"
key = false
