kind = "DojoModel"
class_hash = "0x165b72754ece2bd0a77aabe9ac62976f166283236f915a9fa39aaad833dd3bf"
original_class_hash = "0x165b72754ece2bd0a77aabe9ac62976f166283236f915a9fa39aaad833dd3bf"
abi = "manifests/dev/abis/base/models/contracts_models_assets_communication_communication_tower.json"
name = "contracts::models::assets::communication::communication_tower"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "tower_id"
type = "u32"
key = false

[[members]]
name = "tower_name"
type = "felt252"
key = false

[[members]]
name = "height"
type = "u32"
key = false

[[members]]
name = "status"
type = "felt252"
key = false
