kind = "DojoModel"
class_hash = "0x59c4537294532af6bca5f2e7c745e818bb9c97bce0211850a373846e4a4e4ab"
original_class_hash = "0x59c4537294532af6bca5f2e7c745e818bb9c97bce0211850a373846e4a4e4ab"
abi = "manifests/dev/abis/base/models/contracts_models_units_armored_armored.json"
name = "contracts::models::units::armored::armored"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "accessories"
type = "ArmoredAccessories"
key = false

[[members]]
name = "armored_health"
type = "ArmoredHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false
