kind = "DojoModel"
class_hash = "0x1565dc3692c580dfbb407b06a8d0d6b6afcf7065dce8c848b7639f3d5e4ec55"
original_class_hash = "0x1565dc3692c580dfbb407b06a8d0d6b6afcf7065dce8c848b7639f3d5e4ec55"
abi = "manifests/dev/abis/base/models/contracts_models_transportation_depot.json"
name = "contracts::models::transportation::depot"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "depot_id"
type = "u32"
key = false

[[members]]
name = "depot_name"
type = "felt252"
key = false
