kind = "DojoModel"
class_hash = "0x1dfc37453006e0074c92e5021c419934e8bf9826bf4d189f23a8f1da5603c1"
original_class_hash = "0x1dfc37453006e0074c92e5021c419934e8bf9826bf4d189f23a8f1da5603c1"
abi = "manifests/dev/abis/base/models/contracts_models_assets_financial_bank.json"
name = "contracts::models::assets::financial::bank"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "bank_id"
type = "u32"
key = false

[[members]]
name = "bank_name"
type = "felt252"
key = false

[[members]]
name = "total_deposit"
type = "u32"
key = false

[[members]]
name = "total_withdrawals"
type = "u32"
key = false

[[members]]
name = "interest_rate"
type = "u32"
key = false

[[members]]
name = "status"
type = "FinancialStatus"
key = false
