kind = "DojoModel"
class_hash = "0x4ff50a39c8d7cff3ad9a0877a4cc0609fa057d1b781dd8d3eb7708b4840ed9b"
original_class_hash = "0x4ff50a39c8d7cff3ad9a0877a4cc0609fa057d1b781dd8d3eb7708b4840ed9b"
abi = "manifests/dev/abis/base/models/contracts_models_units_infantry_infantry_health.json"
name = "contracts::models::units::infantry::infantry_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "shield_strength"
type = "u32"
key = false
