kind = "DojoModel"
class_hash = "0x34a3db17638615c578e2483e9ecbf35124a4a56548c9a9343800318b139b50a"
original_class_hash = "0x34a3db17638615c578e2483e9ecbf35124a4a56548c9a9343800318b139b50a"
abi = "manifests/dev/abis/base/models/contracts_models_units_naval_ship.json"
name = "contracts::models::units::naval::ship"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "range"
type = "u256"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "ship_accessories"
type = "ShipAccessories"
key = false

[[members]]
name = "ship_health"
type = "ShipHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false

[[members]]
name = "energy"
type = "u32"
key = false
