kind = "DojoModel"
class_hash = "0xe8d2f1f28a23623d274aff6c423dd1ee9a05d836b5f1cc9d6f6d5eac18879c"
original_class_hash = "0xe8d2f1f28a23623d274aff6c423dd1ee9a05d836b5f1cc9d6f6d5eac18879c"
abi = "manifests/dev/abis/base/models/contracts_models_assets_millitary_armory.json"
name = "contracts::models::assets::millitary::armory"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "armory_id"
type = "u32"
key = false

[[members]]
name = "armory_name"
type = "felt252"
key = false

[[members]]
name = "weapon_inventory"
type = "u32"
key = false

[[members]]
name = "ammo_inventory"
type = "u32"
key = false

[[members]]
name = "status"
type = "MillitaryStatus"
key = false
