kind = "DojoModel"
class_hash = "0x4161272c386d44b2381daaa7e775d4afb781403e7f91653830229175d0fa983"
original_class_hash = "0x4161272c386d44b2381daaa7e775d4afb781403e7f91653830229175d0fa983"
abi = "manifests/dev/abis/base/models/contracts_models_units_infantry_infantry.json"
name = "contracts::models::units::infantry::infantry"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "accessories"
type = "InfantryAccessories"
key = false

[[members]]
name = "health"
type = "InfantryHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false
