kind = "DojoModel"
class_hash = "0x2e2decb4524429525e3991b3c463310678c75cc0d16aad17bc27bafe99f6c08"
original_class_hash = "0x2e2decb4524429525e3991b3c463310678c75cc0d16aad17bc27bafe99f6c08"
abi = "manifests/dev/abis/base/models/contracts_models_units_cyber_cyber_unit_accessories.json"
name = "contracts::models::units::cyber::cyber_unit_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "malware"
type = "u32"
key = false

[[members]]
name = "firewalls"
type = "u32"
key = false

[[members]]
name = "vpn_tokens"
type = "u32"
key = false
