kind = "DojoModel"
class_hash = "0x66a3692714c436e86dcebd5859dec21814c0c1250fa2aa494453f281ec24b85"
original_class_hash = "0x66a3692714c436e86dcebd5859dec21814c0c1250fa2aa494453f281ec24b85"
abi = "manifests/dev/abis/base/models/contracts_models_assets_millitary_barracks.json"
name = "contracts::models::assets::millitary::barracks"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "barracks_id"
type = "u32"
key = false

[[members]]
name = "barrack_name"
type = "felt252"
key = false

[[members]]
name = "capacity"
type = "u32"
key = false

[[members]]
name = "current_soldiers"
type = "u32"
key = false

[[members]]
name = "status"
type = "MillitaryStatus"
key = false
