kind = "DojoModel"
class_hash = "0x1cd98d12fbaa3121ab86b19f505cea53a412925b5f7394144a287533962a8ec"
original_class_hash = "0x1cd98d12fbaa3121ab86b19f505cea53a412925b5f7394144a287533962a8ec"
abi = "manifests/dev/abis/base/models/contracts_models_infantry_position.json"
name = "contracts::models::infantry::position"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "x_coordinate"
type = "u32"
key = false

[[members]]
name = "y_coordinate"
type = "u32"
key = false
