kind = "DojoModel"
class_hash = "0x60b94081609d74d4032133b3844131a8e504e7d10ec40424a9571fe9dfe2736"
original_class_hash = "0x60b94081609d74d4032133b3844131a8e504e7d10ec40424a9571fe9dfe2736"
abi = "manifests/dev/abis/base/models/contracts_models_assets_research_innovation_center.json"
name = "contracts::models::assets::research::innovation_center"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "center_id"
type = "u32"
key = false

[[members]]
name = "center_name"
type = "felt252"
key = false

[[members]]
name = "innovation_points"
type = "u32"
key = false

[[members]]
name = "status"
type = "ResearchStatus"
key = false
