kind = "DojoModel"
class_hash = "0x327eb29467d0d3017a155f71458b63e8f6906cebb3a9cbc4155da6b4cd204cb"
original_class_hash = "0x327eb29467d0d3017a155f71458b63e8f6906cebb3a9cbc4155da6b4cd204cb"
abi = "manifests/dev/abis/base/models/contracts_models_assets_intelligence_intelligence_agency.json"
name = "contracts::models::assets::intelligence::intelligence_agency"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "agency_id"
type = "u32"
key = false

[[members]]
name = "agency_name"
type = "felt252"
key = false

[[members]]
name = "agency_type"
type = "AgencyType"
key = false

[[members]]
name = "resource_allocation"
type = "u32"
key = false

[[members]]
name = "status"
type = "AgencyStatus"
key = false
