kind = "DojoModel"
class_hash = "0x27058327de7d987b08cc3a31dc70fae900e8dadfc7f7627358d3ccab7b5a7d8"
original_class_hash = "0x27058327de7d987b08cc3a31dc70fae900e8dadfc7f7627358d3ccab7b5a7d8"
abi = "manifests/dev/abis/base/models/contracts_models_assets_energy_nuclear_power_station.json"
name = "contracts::models::assets::energy::nuclear_power_station"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "station_id"
type = "u32"
key = false

[[members]]
name = "station_name"
type = "felt252"
key = false

[[members]]
name = "power_output"
type = "u32"
key = false

[[members]]
name = "fuel_level"
type = "u32"
key = false

[[members]]
name = "status"
type = "EnergyStatus"
key = false
