kind = "DojoModel"
class_hash = "0x606e631945cdf20ecd398841ab5b7548abe4fdfe32912c120560338cea6c29c"
original_class_hash = "0x606e631945cdf20ecd398841ab5b7548abe4fdfe32912c120560338cea6c29c"
abi = "manifests/dev/abis/base/models/contracts_models_player_player.json"
name = "contracts::models::player::player"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "index"
type = "u32"
key = true

[[members]]
name = "address"
type = "starknet::ContractAddress"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "supply"
type = "UnitsSupply"
key = false

[[members]]
name = "last_action"
type = "u64"
key = false

[[members]]
name = "rank"
type = "u8"
key = false

[[members]]
name = "player_score"
type = "PlayerScore"
key = false
