kind = "DojoModel"
class_hash = "0x6d20eb9681b4a2a6172b48cba449b991ec87146db426511f4f0b10ce0ab2b8b"
original_class_hash = "0x6d20eb9681b4a2a6172b48cba449b991ec87146db426511f4f0b10ce0ab2b8b"
abi = "manifests/dev/abis/base/models/contracts_models_assets_energy_solar_power_plant.json"
name = "contracts::models::assets::energy::solar_power_plant"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "plant_id"
type = "u32"
key = false

[[members]]
name = "plant_name"
type = "u32"
key = false

[[members]]
name = "power_output"
type = "felt252"
key = false

[[members]]
name = "status"
type = "EnergyStatus"
key = false
