kind = "DojoModel"
class_hash = "0x787c5a8625289f5eb48bf94784ffc38e987bbe6c39c8731439e8154ed048115"
original_class_hash = "0x787c5a8625289f5eb48bf94784ffc38e987bbe6c39c8731439e8154ed048115"
abi = "manifests/dev/abis/base/models/contracts_models_units_armored_armored_health.json"
name = "contracts::models::units::armored::armored_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "shield_strength"
type = "u32"
key = false
