kind = "DojoModel"
class_hash = "0x7498881329435dd7579357ef2cbfebc50f1d4afa2982526450cb76b7e510a4f"
original_class_hash = "0x7498881329435dd7579357ef2cbfebc50f1d4afa2982526450cb76b7e510a4f"
abi = "manifests/dev/abis/base/models/contracts_models_assets_transportation_depot.json"
name = "contracts::models::assets::transportation::depot"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "depot_id"
type = "u32"
key = false

[[members]]
name = "depot_name"
type = "felt252"
key = false
