kind = "DojoModel"
class_hash = "0x46384f77afdf6d58d389c22b3837afb9afd83e599e76bee77d2057d8be498fe"
original_class_hash = "0x46384f77afdf6d58d389c22b3837afb9afd83e599e76bee77d2057d8be498fe"
abi = "manifests/dev/abis/base/models/contracts_models_units_ship_ship_health.json"
name = "contracts::models::units::ship::ship_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "hull_integrity"
type = "u32"
key = false

[[members]]
name = "shield_strength"
type = "u32"
key = false
