kind = "DojoModel"
class_hash = "0x20d18bc3a0cc623cf15e286cc347ba204dd0c99c3f5dc71983c3b99ece07836"
original_class_hash = "0x20d18bc3a0cc623cf15e286cc347ba204dd0c99c3f5dc71983c3b99ece07836"
abi = "manifests/dev/abis/base/models/contracts_models_assets_intelligence_spy_network.json"
name = "contracts::models::assets::intelligence::spy_network"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "network_id"
type = "u32"
key = false

[[members]]
name = "network_name"
type = "felt252"
key = false

[[members]]
name = "number_of_spies"
type = "u32"
key = false

[[members]]
name = "intel_reliability"
type = "u32"
key = false

[[members]]
name = "status"
type = "AgencyStatus"
key = false
