kind = "DojoModel"
class_hash = "0x2d47355f98420caca20c95dd039670adeea74cfbe77782eedf43b8b9e0a28d4"
original_class_hash = "0x2d47355f98420caca20c95dd039670adeea74cfbe77782eedf43b8b9e0a28d4"
abi = "manifests/dev/abis/base/models/contracts_models_assets_financial_stock_exchange.json"
name = "contracts::models::assets::financial::stock_exchange"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "exchange_id"
type = "u32"
key = false

[[members]]
name = "exchange_name"
type = "felt252"
key = false

[[members]]
name = "listed_companies"
type = "u32"
key = false

[[members]]
name = "trading_volume"
type = "u32"
key = false

[[members]]
name = "status"
type = "FinancialStatus"
key = false
