kind = "DojoModel"
class_hash = "0x7b92c9e9e4aa710c87e1231abe95f454898f93eea077f12c249afbd7eba7552"
original_class_hash = "0x7b92c9e9e4aa710c87e1231abe95f454898f93eea077f12c249afbd7eba7552"
abi = "manifests/dev/abis/base/models/contracts_models_assets_research_laboratory.json"
name = "contracts::models::assets::research::laboratory"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "lab_id"
type = "u32"
key = false

[[members]]
name = "lab_name"
type = "felt252"
key = false

[[members]]
name = "research_capacity"
type = "u32"
key = false

[[members]]
name = "ongoing_projects"
type = "u32"
key = false

[[members]]
name = "status"
type = "ResearchStatus"
key = false
