kind = "DojoModel"
class_hash = "0x74562fd47d50a63696f2c2ecba5f43f92a42ab5217afd3ac8165d92d94a459a"
original_class_hash = "0x74562fd47d50a63696f2c2ecba5f43f92a42ab5217afd3ac8165d92d94a459a"
abi = "manifests/dev/abis/base/models/contracts_models_units_cyber_cyber_unit.json"
name = "contracts::models::units::cyber::cyber_unit"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "hacking_range"
type = "u64"
key = false

[[members]]
name = "encryption_strength"
type = "u32"
key = false

[[members]]
name = "stealth"
type = "u8"
key = false

[[members]]
name = "accessories"
type = "CyberUnitAccessories"
key = false

[[members]]
name = "health"
type = "CyberUnitHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false

[[members]]
name = "bandwidth"
type = "u32"
key = false

[[members]]
name = "processing_power"
type = "u32"
key = false
