kind = "DojoModel"
class_hash = "0x6b954694d10974e6eb6ed51ecf0a79d1e1bbd0abed9af1694a5e171a980ba8e"
original_class_hash = "0x6b954694d10974e6eb6ed51ecf0a79d1e1bbd0abed9af1694a5e171a980ba8e"
abi = "manifests/dev/abis/base/models/contracts_models_units_unitsupply_units_supply.json"
name = "contracts::models::units::unitsupply::units_supply"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "infantry"
type = "u32"
key = false

[[members]]
name = "armored"
type = "u32"
key = false

[[members]]
name = "air"
type = "u32"
key = false

[[members]]
name = "naval"
type = "u32"
key = false

[[members]]
name = "cyber"
type = "u32"
key = false
