kind = "DojoModel"
class_hash = "0x35139546214535b815bc206a40ab54445ef1eca1ea5fbf4aa97625ba7d0015f"
original_class_hash = "0x35139546214535b815bc206a40ab54445ef1eca1ea5fbf4aa97625ba7d0015f"
abi = "manifests/dev/abis/base/models/contracts_models_units_armored_armored_accessories.json"
name = "contracts::models::units::armored::armored_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "fuel"
type = "u32"
key = false

[[members]]
name = "ammunition"
type = "u32"
key = false
