kind = "DojoModel"
class_hash = "0x616615d5fb55675d1bba2db102bff3ccb702d748807652832825b192eba6a78"
original_class_hash = "0x616615d5fb55675d1bba2db102bff3ccb702d748807652832825b192eba6a78"
abi = "manifests/dev/abis/base/models/contracts_models_amored_amored.json"
name = "contracts::models::amored::amored"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "accessories"
type = "AmoredAccessories"
key = false

[[members]]
name = "Amored_health"
type = "AmoredHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false
