kind = "DojoModel"
class_hash = "0x7ec238362b38badad123eade33975dad42f65976faf713f88cc409e6e97b878"
original_class_hash = "0x7ec238362b38badad123eade33975dad42f65976faf713f88cc409e6e97b878"
abi = "manifests/dev/abis/base/models/contracts_models_transportation_railway_station.json"
name = "contracts::models::transportation::railway_station"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "station_id"
type = "u32"
key = false

[[members]]
name = "station_name"
type = "felt252"
key = false
