kind = "DojoModel"
class_hash = "0x23adcdfcdf6117e2a0607ac52210ccfb5e562ddab7fbd9fa3ea67f6b9018a49"
original_class_hash = "0x23adcdfcdf6117e2a0607ac52210ccfb5e562ddab7fbd9fa3ea67f6b9018a49"
abi = "manifests/dev/abis/base/models/contracts_models_units_cyber_cyber_unit_health.json"
name = "contracts::models::units::cyber::cyber_unit_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "system_integrity"
type = "u32"
key = false

[[members]]
name = "anti_virus_strength"
type = "u32"
key = false
