kind = "DojoModel"
class_hash = "0x6ea1d2f894e67b4754ad65b4c6368705b4c341f64126815592c09d4b5110582"
original_class_hash = "0x6ea1d2f894e67b4754ad65b4c6368705b4c341f64126815592c09d4b5110582"
abi = "manifests/dev/abis/base/models/contracts_models_ship_ship_accessories.json"
name = "contracts::models::ship::ship_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "fuel"
type = "u32"
key = false

[[members]]
name = "ammunition"
type = "u32"
key = false
