kind = "DojoModel"
class_hash = "0x10fc1f799aeea1972f618f317f93b9b38fe17c062ea3146cf021dc640e30d10"
original_class_hash = "0x10fc1f799aeea1972f618f317f93b9b38fe17c062ea3146cf021dc640e30d10"
abi = "manifests/dev/abis/base/models/contracts_models_units_unit_states_unit_state.json"
name = "contracts::models::units::unit_states::unit_state"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "unit_type"
type = "u8"
key = true

[[members]]
name = "x"
type = "u256"
key = false

[[members]]
name = "y"
type = "u256"
key = false

[[members]]
name = "z"
type = "u256"
key = false

[[members]]
name = "mode"
type = "UnitMode"
key = false

[[members]]
name = "environment"
type = "EnvironmentInfo"
key = false
