kind = "DojoModel"
class_hash = "0x1fd8107e70b1ac92c7703dcf01accd24a5325ab4ec45ae5fc1d46616401e1c0"
original_class_hash = "0x1fd8107e70b1ac92c7703dcf01accd24a5325ab4ec45ae5fc1d46616401e1c0"
abi = "manifests/dev/abis/base/models/contracts_models_units_air_air_unit_health.json"
name = "contracts::models::units::air::air_unit_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "hull_integrity"
type = "u32"
key = false

[[members]]
name = "engine_health"
type = "u32"
key = false
