kind = "DojoModel"
class_hash = "0x288ae882f9a026e9e3626f1b9b00afa7fd4b1f51bc06bf741291a85f9f3ca34"
original_class_hash = "0x288ae882f9a026e9e3626f1b9b00afa7fd4b1f51bc06bf741291a85f9f3ca34"
abi = "manifests/dev/abis/base/models/contracts_models_assets_energy_oil_depot.json"
name = "contracts::models::assets::energy::oil_depot"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "depot_id"
type = "u32"
key = false

[[members]]
name = "depot_name"
type = "felt252"
key = false

[[members]]
name = "capacity"
type = "u32"
key = false

[[members]]
name = "current_storage"
type = "u32"
key = false

[[members]]
name = "status"
type = "EnergyStatus"
key = false
