kind = "DojoModel"
class_hash = "0x14f2a6a2f53f204e95f3a75f6d964333571c79f47a7af31dfe4b3e0aeacdc04"
original_class_hash = "0x14f2a6a2f53f204e95f3a75f6d964333571c79f47a7af31dfe4b3e0aeacdc04"
abi = "manifests/dev/abis/base/models/contracts_models_infantry_infantry_health.json"
name = "contracts::models::infantry::infantry_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "shield_strength"
type = "u32"
key = false
