kind = "DojoModel"
class_hash = "0x578ab05d9f3575be04dfafb26247596a8c7c6da7d1f84ed54b6ed5f96a1f755"
original_class_hash = "0x578ab05d9f3575be04dfafb26247596a8c7c6da7d1f84ed54b6ed5f96a1f755"
abi = "manifests/dev/abis/base/models/contracts_models_units_naval_ship.json"
name = "contracts::models::units::naval::ship"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "ship_accessories"
type = "ShipAccessories"
key = false

[[members]]
name = "ship_health"
type = "ShipHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false
