kind = "DojoModel"
class_hash = "0x39e40a951c55df8185455b5b2f733f75939e9dab1dda124881d9cd9810072e4"
original_class_hash = "0x39e40a951c55df8185455b5b2f733f75939e9dab1dda124881d9cd9810072e4"
abi = "manifests/dev/abis/base/models/contracts_models_assets_research_testing_ground.json"
name = "contracts::models::assets::research::testing_ground"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "ground_id"
type = "u32"
key = false

[[members]]
name = "ground_name"
type = "felt252"
key = false

[[members]]
name = "test_capacity"
type = "u32"
key = false

[[members]]
name = "ongiong_tests"
type = "u32"
key = false

[[members]]
name = "status"
type = "ResearchStatus"
key = false
