kind = "DojoModel"
class_hash = "0x17f043ca3742be115a67b97ebf8e873a5ea20c701f0e1adb46142ec99b6d2cb"
original_class_hash = "0x17f043ca3742be115a67b97ebf8e873a5ea20c701f0e1adb46142ec99b6d2cb"
abi = "manifests/dev/abis/base/models/contracts_models_units_playerstate_units_supply.json"
name = "contracts::models::units::playerstate::units_supply"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "infantry"
type = "u32"
key = false

[[members]]
name = "armored"
type = "u32"
key = false

[[members]]
name = "air"
type = "u32"
key = false

[[members]]
name = "naval"
type = "u32"
key = false

[[members]]
name = "cyber"
type = "u32"
key = false
