kind = "DojoModel"
class_hash = "0x6a8365e69d2df781ba482e88a8c01e42c6e6e5f05dcfb36e12aeeea58d04352"
original_class_hash = "0x6a8365e69d2df781ba482e88a8c01e42c6e6e5f05dcfb36e12aeeea58d04352"
abi = "manifests/dev/abis/base/models/contracts_models_amored_amored_accessories.json"
name = "contracts::models::amored::amored_accessories"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "fuel"
type = "u32"
key = false

[[members]]
name = "ammunition"
type = "u32"
key = false
