kind = "DojoModel"
class_hash = "0x53f9a0bcc9c37aad9e420cd835b4356ee23e2d91d64740844162de3190ca5c8"
original_class_hash = "0x53f9a0bcc9c37aad9e420cd835b4356ee23e2d91d64740844162de3190ca5c8"
abi = "manifests/dev/abis/base/models/contracts_models_position_position.json"
name = "contracts::models::position::position"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "vec"
type = "Vec3"
key = false
