kind = "DojoModel"
class_hash = "0x4f5265e7e651dc8d0ff5f608e39389b3331f93a82a7a8e116f10f6708f827e4"
original_class_hash = "0x4f5265e7e651dc8d0ff5f608e39389b3331f93a82a7a8e116f10f6708f827e4"
abi = "manifests/dev/abis/base/models/contracts_models_assets_financial_treasury.json"
name = "contracts::models::assets::financial::treasury"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "treasury_id"
type = "u32"
key = false

[[members]]
name = "treasury_name"
type = "felt252"
key = false

[[members]]
name = "funds_available"
type = "u32"
key = false

[[members]]
name = "funds_reserved"
type = "u32"
key = false

[[members]]
name = "status"
type = "FinancialStatus"
key = false
