kind = "DojoModel"
class_hash = "0x6c20e598c1f2862fc721c3785ded0561c29573b0f7091cf88dd6399bc784d05"
original_class_hash = "0x6c20e598c1f2862fc721c3785ded0561c29573b0f7091cf88dd6399bc784d05"
abi = "manifests/dev/abis/base/models/contracts_models_ship_ship.json"
name = "contracts::models::ship::ship"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "range"
type = "u64"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "ship_accessories"
type = "ShipAccessories"
key = false

[[members]]
name = "ship_health"
type = "ShipHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false
