kind = "DojoModel"
class_hash = "0x64aade2c32a1f6f5dfeab27ca8fe4de17a223eea17fe7dc09021e8b702c9161"
original_class_hash = "0x64aade2c32a1f6f5dfeab27ca8fe4de17a223eea17fe7dc09021e8b702c9161"
abi = "manifests/dev/abis/base/models/contracts_models_units_air_air_unit.json"
name = "contracts::models::units::air::air_unit"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "unit_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "range"
type = "u256"
key = false

[[members]]
name = "firepower"
type = "u32"
key = false

[[members]]
name = "accuracy"
type = "u8"
key = false

[[members]]
name = "energy"
type = "u32"
key = false

[[members]]
name = "accessories"
type = "AirUnitAccessories"
key = false

[[members]]
name = "health"
type = "AirUnitHealth"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "battlefield_name"
type = "BattlefieldName"
key = false

[[members]]
name = "altitude"
type = "u32"
key = false

[[members]]
name = "max_speed"
type = "u32"
key = false
