kind = "DojoModel"
class_hash = "0x667cb861cd0453d796f03bcbde8c33659171c242fd2476804b86833eb0fea91"
original_class_hash = "0x667cb861cd0453d796f03bcbde8c33659171c242fd2476804b86833eb0fea91"
abi = "manifests/dev/abis/base/models/contracts_models_transportation_airport.json"
name = "contracts::models::transportation::airport"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "airport_id"
type = "u32"
key = false

[[members]]
name = "airport_name"
type = "felt252"
key = false
