kind = "DojoModel"
class_hash = "0x283f9329f76eeddc5a5b798f36d08d99ca1fce0513e9dd1a6c3c1a5335eb635"
original_class_hash = "0x283f9329f76eeddc5a5b798f36d08d99ca1fce0513e9dd1a6c3c1a5335eb635"
abi = "manifests/dev/abis/base/models/contracts_models_units_playerstate_player_state.json"
name = "contracts::models::units::playerstate::player_state"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "supply"
type = "UnitsSupply"
key = false
