kind = "DojoModel"
class_hash = "0x15ec4adfeaeb4d66e1196f04efc730cdb9ae6e380fd17c4cab287cc3fdf04ec"
original_class_hash = "0x15ec4adfeaeb4d66e1196f04efc730cdb9ae6e380fd17c4cab287cc3fdf04ec"
abi = "manifests/dev/abis/base/models/contracts_models_assets_millitary_command_center.json"
name = "contracts::models::assets::millitary::command_center"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "center_id"
type = "u32"
key = false

[[members]]
name = "center_name"
type = "felt252"
key = false

[[members]]
name = "coordination_level"
type = "u32"
key = false

[[members]]
name = "status"
type = "MillitaryStatus"
key = false
