kind = "DojoModel"
class_hash = "0x1eede52864d89750c740a597971f74bd3955f49ee16a6bc012d81cb9f54123f"
original_class_hash = "0x1eede52864d89750c740a597971f74bd3955f49ee16a6bc012d81cb9f54123f"
abi = "manifests/dev/abis/base/models/contracts_models_units_naval_ship_health.json"
name = "contracts::models::units::naval::ship_health"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "u32"
key = true

[[members]]
name = "hull_integrity"
type = "u32"
key = false

[[members]]
name = "shield_strength"
type = "u32"
key = false
