kind = "DojoContract"
class_hash = "0x482c15ea1ecee157178e49b3310ae5410a688e1905468c31a32f713ed595ca"
original_class_hash = "0x482c15ea1ecee157178e49b3310ae5410a688e1905468c31a32f713ed595ca"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_nexus_nexus.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::nexus::nexus"
