kind = "DojoContract"
class_hash = "0x69e8a8d797d6e360bfa0af0dd339c0153b0bef43c1657115aa38ca48953a154"
original_class_hash = "0x69e8a8d797d6e360bfa0af0dd339c0153b0bef43c1657115aa38ca48953a154"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_arena_arena.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::arena::arena"
