kind = "DojoContract"
class_hash = "0x730963c622f6e7bf9f705fc7b3361f4d2b45fcf0a9788e22eacf7570348645d"
original_class_hash = "0x730963c622f6e7bf9f705fc7b3361f4d2b45fcf0a9788e22eacf7570348645d"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_arena_Arena.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::arena::Arena"
