kind = "DojoContract"
class_hash = "0x3ef4127f52e4407b4cfaecd66f3634f5ac3ff01068703ff9813c8294f82032f"
original_class_hash = "0x3ef4127f52e4407b4cfaecd66f3634f5ac3ff01068703ff9813c8294f82032f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_nexus_nexus.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::nexus::nexus"
