kind = "DojoContract"
class_hash = "0x65023afaf3693c3350580854af1fe0cf050fa795ff5008981cfb074f168314e"
original_class_hash = "0x65023afaf3693c3350580854af1fe0cf050fa795ff5008981cfb074f168314e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_host_host.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::arena::arena"
