kind = "DojoContract"
class_hash = "0x2d86d302950399b9372463cfb29696d48fdea98fdc41754181dc956cf662481"
original_class_hash = "0x2d86d302950399b9372463cfb29696d48fdea98fdc41754181dc956cf662481"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/contracts_systems_nexus_nexus.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "contracts::systems::nexus::nexus"
